import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`
          #__next-build-watcher { display: none !important; }
          #NextLogo { display: none !important; }
          #nextjs-portal-root { display: none !important; }
          [data-nextjs-dialog-overlay] { display: none !important; }
          [data-nextjs-dialog] { display: none !important; }
        `}</style>
      </head>
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
